project_name: go-fast-cdn

dist: .dist

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    binary: go-fast-cdn
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm

release:
  draft: true

archives:
  - format: zip
    files:
      - LICENSE*
      - CHANGELOG*

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
