version: 2

project_name: go-fast-cdn

dist: .dist

before:
  hooks:
    - go mod tidy

builds:
  - id: linux-amd64
    binary: go-fast-cdn
    env:
      - CGO_ENABLED=1
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    goos:
      - linux
    goarch:
      - amd64
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser

  - id: linux-arm64
    binary: go-fast-cdn
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    goos:
      - linux
    goarch:
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser

  - id: linux-armv7
    binary: go-fast-cdn
    env:
      - CGO_ENABLED=1
      - CC=arm-linux-gnueabihf-gcc
      - CXX=arm-linux-gnueabihf-g++
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 7
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser

  - id: darwin-amd64
    binary: go-fast-cdn
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    goos:
      - darwin
    goarch:
      - amd64
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser

  - id: darwin-arm64
    binary: go-fast-cdn
    env:
      - CGO_ENABLED=1
      - CC=oa64-clang
      - CXX=oa64-clang++
    goos:
      - darwin
    goarch:
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser

  - id: windows-amd64
    binary: go-fast-cdn
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goos:
      - windows
    goarch:
      - amd64
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser

universal_binaries:
  - id: darwin
    ids:
      - darwin-amd64
      - darwin-arm64
    name_template: '{{ .ProjectName }}'
    replace: true

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    wrap_in_directory: true
    files:
      - LICENSE*
      - CHANGELOG*
      - README*

nfpms:
  - id: packages
    package_name: go-fast-cdn
    vendor: Kevin Nielsen
    homepage: https://github.com/kevinanielsen/go-fast-cdn
    maintainer: Kevin Nielsen <kevin@email.com>
    description: Fast and simple Open Source CDN
    license: MIT
    formats:
      - deb
      - rpm
      - apk

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

release:
  target_commitish: '{{ .Commit }}'
  draft: true
  github:
    owner: kevinanielsen
    name: go-fast-cdn
  name_template: "{{.ProjectName}}-v{{.Version}}"
  header: |
    ## Changes

    Welcome to this new release!

changelog:
  sort: asc
  use: git
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: Dependency updates
      regexp: '^.*?(feat|fix)\(deps\)!?:.+$'
      order: 300
    - title: "New Features"
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 100
    - title: "Security updates"
      regexp: '^.*?sec(\(.+\))??!?:.+$'
      order: 150
    - title: "Bug fixes"
      regexp: '^.*?fix(\(.+\))??!?:.+$'
      order: 200
    - title: "Documentation updates"
      regexp: ^.*?doc(\(.+\))??!?:.+$
      order: 400
    - title: "Build process updates"
      regexp: ^.*?build(\(.+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999

metadata:
  mod_timestamp: '{{ .CommitTimestamp }}'