project_name: go-fast-cdn

dist: .dist

before:
  hooks:
    - go mod tidy

builds:
  - id: "linux"
    env:
      - CGO_ENABLED=1
    binary: go-fast-cdn
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
    tags:
      - webp

  - id: "other"
    env:
      - CGO_ENABLED=0
    binary: go-fast-cdn
    goos:
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
    tags:
      - nowebp

release:
  target_commitish: '{{ .Commit }}'
  draft: true
  github:
    owner: kevinanielsen
    name: go-fast-cdn

archives:
  - format: zip
    files:
      - LICENSE*
      - CHANGELOG*

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
