name: release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "New tag name"
        required: true
  push:
    tags:
      - "*"

permissions:
  contents: write
  packages: write
  issues: write
  id-token: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create and push tag
        if: github.event.inputs.tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ github.event.inputs.tag }}
          git push origin ${{ github.event.inputs.tag }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: ui/pnpm-lock.yaml

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.21.3"

      - name: Build UI Dashboard
        run: pnpm --dir=./ui install && pnpm --dir=./ui build

      - name: Tidy modules
        run: go mod tidy

      - name: Run tests
        run: go test ./...

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run GoReleaser with goreleaser-cross
        run: |
          docker run --rm --privileged \
            -v ${{ github.workspace }}:/go/src/github.com/kevinanielsen/go-fast-cdn \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -w /go/src/github.com/kevinanielsen/go-fast-cdn \
            -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            -e CGO_ENABLED=1 \
            goreleaser/goreleaser-cross:v1.27.0 \
            release --clean
